-- Per-user service catalog.
--
-- Run once in the Supabase SQL Editor. It is idempotent where possible.
--
-- Design:
--   servicios_catalogo  -> global list of service TYPES (name, description,
--                          quotation variable). No prices here.
--   usuario_servicio    -> bridge: each user offers a subset of the types with
--                          their own precio_base / limite_operativo / activo.

-- 1) Global catalog: remove per-user columns -------------------------------
-- WARNING: this DROPS data. precio_base, limite_operativo and activo are being
-- moved to usuario_servicio. Confirm that servicios_catalogo has no data worth
-- keeping before running this block (the table was unused by application code).
ALTER TABLE public.servicios_catalogo
  DROP COLUMN IF EXISTS precio_base,
  DROP COLUMN IF EXISTS limite_operativo,
  DROP COLUMN IF EXISTS activo;

-- Unique service name (needed for the idempotent seed below).
-- If the table already holds duplicated names this will fail: clean them first.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.servicios_catalogo'::regclass
      AND conname = 'servicios_catalogo_nombre_key'
  ) THEN
    ALTER TABLE public.servicios_catalogo
      ADD CONSTRAINT servicios_catalogo_nombre_key UNIQUE (nombre);
  END IF;
END $$;

-- 2) Bridge table -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.usuario_servicio (
  id_usuario_servicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario          BIGINT NOT NULL REFERENCES public.usuarios (id),
  id_servicio         BIGINT NOT NULL REFERENCES public.servicios_catalogo (id_servicio),
  precio_base         NUMERIC(12, 2) NOT NULL CHECK (precio_base >= 0),
  limite_operativo    NUMERIC,
  activo              BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (id_usuario, id_servicio)
);
-- NOTE: if servicios_catalogo.id_servicio is not BIGINT (e.g. INTEGER), adjust
-- the id_servicio column type above so the foreign key can be created.
-- limite_operativo has no unit defined yet (placeholder: plain numeric).

CREATE INDEX IF NOT EXISTS usuario_servicio_usuario_idx
  ON public.usuario_servicio (id_usuario);

-- 3) Seed: the 6 service types ---------------------------------------------
-- descripcion and variable_cotizacion values are PLACEHOLDERS: review and edit
-- them before (or after) running. Re-running does not overwrite edited rows.
INSERT INTO public.servicios_catalogo (nombre, descripcion, variable_cotizacion)
VALUES
  ('Mantenimiento regular de césped', 'Placeholder: corte y mantenimiento periódico del césped', 'superficie_mantenible'),
  ('Desmalezado',                     'Placeholder: eliminación de malezas y vegetación no deseada', 'superficie_mantenible'),
  ('Jardinería y cultivo',            'Placeholder: cuidado de canteros, huerta y plantas', 'superficie_mantenible'),
  ('Plantado de especies',            'Placeholder: plantación de especies vegetales', 'cantidad'),
  ('Poda de árboles',                 'Placeholder: poda de árboles y arbustos', 'cantidad'),
  ('Limpieza de espacios',            'Placeholder: limpieza general de espacios exteriores', 'superficie_total')
ON CONFLICT (nombre) DO NOTHING;

-- 4) Example (commented out): assign all 6 services to one user -------------
-- Replace 1 with the target usuarios.id and adjust the price / limit.
-- INSERT INTO public.usuario_servicio (id_usuario, id_servicio, precio_base, limite_operativo)
-- SELECT 1, s.id_servicio, 0, NULL
-- FROM public.servicios_catalogo s
-- ON CONFLICT (id_usuario, id_servicio) DO NOTHING;
